### ISSUE TITLE
Feature request: Add not activated examples 

### ISSUE THREAD

**Issue by Berchemer** [Scrounger/ioBroker.linux-control#34]
Thanks for your work 😀
For the Future I would find it nice:
Please add examples that are frequently requested in the forum (or as you already do that in the documentation) in an not activated form to the adapter-configuration.
In particular, I would be interested in one or more examples of backing up (copying) files from a host directory to an SMB share on the network or to an FTP drive.
And maybe a German documentation, matching the English, wouldn't be so bad either ;-)

**Comment by Scrounger** [comment]
Sorry but that would be very time consuming due to the many different linux distibutions. That's what the forum is for.

> In particular, I would be interested in one or more examples of backing up (copying) files from a host directory to an SMB share on the network or to an FTP drive. And maybe a German documentation, matching the English, wouldn't be so bad either ;-)

For something like this I would write a linux bash script and not let the adapter do it. Then you can also include in the script that when successfully executed or error, for example, via simple api / rest api that is transmitted to iob
